### PR TITLE
Use WideLineBuffer for contour surfaces

### PR DESCRIPTION
**Pull request by fredludlow**
Addresses #446, but probably want to take a good look at results before deciding whether to merge

I've replaced the `ContourBuffer` with `WideLineBuffer` in `MolecularSurfaceRepresentation` and `SurfaceRepresentation`. 

This version does it with a simple function for converting mesh data to line data (in `surface-utils.js`) rather than the way we discussed in #446 . It would be a little more efficient to write the correct output in marching-cubes, but it seemed to need a lot of other changes to the Surface class and the two representation classes to accommodate doing it that way. Performance seems to be okay doing it this way... What do you think?

The representation/molecularsurface-av and test/xray demos are a good comparison of changed behaviour:
Xray:
http://nglviewer.org/ts2/?script=test/xray
http://fredludlow.com/ngl/contour-width/examples/webapp.html?script=test/xray

Surface:
http://nglviewer.org/ts2/?script=representation/molecularsurface-av
http://fredludlow.com/ngl/contour-width/examples/webapp.html?script=representation/molecularsurface-av
NB changed the ligand surface to linewidth:2 to demo feature

At linewidth: 1.0 it looks a little jagged, maybe default should be higher? Or is there a way to render narrow lines a bit more smoothly?

### CODE REVIEW

**Comment by arose** [comment]
Thanks for taking a stab at this @fredludlow!

http://fredludlow.com/ngl/contour-width/examples/webapp.html?script=test/xray seems broken.

**Comment by fredludlow** [comment]
Hmm, it's working for me - is the example broken or server inaccessible?

**Comment by fredludlow** [comment]
@arose - is the example still broken for you? (Still working here...)

**Comment by arose** [comment]
it works, i wanted to add reuse of gl buffers for wideline shader because it is somewhat slow when recalculating a mesh when moving around

**Comment by fredludlow** [comment]
I'm closing this as I think it's not very performant and I've stopped using it locally, but can resurrect it if there's interest later. There's also a bug with not reallocating arrays when the input data gets bigger (so maps get truncated).

**Pull request closed without merging**
