### PR TITLE
Fix/update package dependencies

### PR DESCRIPTION
**Pull request by garyo**
This removes some dependencies on vulnerable old packages such as old versions of core-js.
This should apply cleanly on top of my previous pull request -- only the last commit, ece8274a, is part of this one. If not, I'll rebase and push again.

### CODE REVIEW

**Comment by bergwerf** [comment]
@ppillot could you look at this? I would like to update more dependencies (in particular typedoc, see #617) but perhaps it is easier if this is merged first.

**Comment by fredludlow** [comment]
There's a minor regression from #716, which introduces `WebGL2RenderingContext`. This isn't supported in IE11 or Safari on iOS, but the only times it is used are to access the DYNAMIC_DRAW enum member, which is also available on WebGLRenderingContext. So, rather than make a whole PR and cause rebasing faff, do you think you could add the change (there's 6 occurences of WebGL2RenderingContext->WebGLRenderingContext in buffer.ts)?

**Comment by garyo** [comment]
> do you think you could add the change (there's 6 occurences of WebGL2RenderingContext->WebGLRenderingContext in buffer.ts)?

Sure, no problem. Will do.

**Comment by fredludlow** [comment]
Thanks! Do you want to hit merge (I guess on the others first?)

**Pull request merged**
