### PR TITLE
Stl binary

### PR DESCRIPTION
**Pull request by ppillot**
binary stl writer + tests

### CODE REVIEW

**Comment by arose** [comment]
there is an error with the test, can you have alook at that, thanks

**Comment by ppillot** [comment]
Wooops! a problem with little endianess in the test... Should be fixed now

**Comment by arose** [comment]
thanks @ppillot, I merged it and gave using the IOBuffer a try for writing the stl data. Hope you don't mind. I like it, it is less boilerplate code

**Comment by ppillot** [comment]
No worries, I didn't know what to do with IOBuffer when you suggested it (!). Looks fine like that.

**Pull request merged**
