### PR TITLE
Fixed Bitset.flip_all()

### PR DESCRIPTION
**Pull request by ppillot**
takes into account bit set length

### CODE REVIEW

**Comment by arose** [comment]
Cool, thanks for tracking this down. Does it fix #274?

**Comment by ppillot** [comment]
I don't think so... I've fixed it because it created a problem: I relied on `flip_all()` to perform an inversion of selection (such as "select not selected") and the set I get had an increase in size, preventing it to be compared with other sets.

**Comment by ppillot** [comment]
Updated PR fixes #274 (would have preferred to make a separate PR, but got mixed between commits...)

**Comment by arose** [comment]
Happy to merge it if you can remove `this.atomSetCache[ seleString ].clone();`.

**Comment by ppillot** [comment]
Done!

**Comment by arose** [comment]
thanks!

**Comment by ppillot** [comment]
My pleasure!

**Pull request merged**
