### PR TITLE
 fix: relative css position for preventing bug in annotations #461

### PR DESCRIPTION
**Pull request by ppillot**
For this fix to work I had to add a wrapper div to canvas and annotations. Without this wrapper, we'd have to directly change the css positioning for the container provided by the user and this could lead to side effects for the user (e.g. if the user sets another positioning style for its container).
This fix doesn't solve the issue of annotations displayed outside of their container element.

### CODE REVIEW

**Comment by ppillot** [comment]
Added a new commit to the PR with a fix for the annotations outside of the viewport.

**Comment by ppillot** [comment]
last fix for a small annotation overflow at the bottom of the viewport. The overflow styling is now on the user provided container (not the wrapper), as the wrapper has a few extra pixels in height.

**Comment by arose** [comment]
thanks, will test tomorrow

**Comment by arose** [comment]
Hi, reverted it. It does not work when the users does not supply an Element or an element id.

**Comment by ppillot** [comment]
Sorry about that, I'll investigate further and make the relevant test cases.
By the way, to improve code clarity, I could create an extra object in stage: there is already `this.container`, but I would like to add `this.wrapper` as an internal reference to the additional div created for positioning the annotations.

**Comment by arose** [comment]
> there is already this.container, but I would like to add this.wrapper as an internal reference to the additional div created for positioning the annotations.

sounds good, I like being very explicit, especially if it does not matter performance wise

**Comment by ppillot** [comment]
Hi, what is the expected behaviour if no HTML Element or element id is provided?
I've checked with latest version and nothing is displayed on screen (but the stage object is created and includes an actual reference to a container element).

Additional question: what shall be done regarding tooltips? They are displayed on top of everything else and can overflow the viewer. I think this behaviour is nice as a cropped tooltip would not be informative, so I would favour keeping tooltips as they are.

**Comment by arose** [comment]
> Hi, what is the expected behaviour if no HTML Element or element id is provided?
I've checked with latest version and nothing is displayed on screen (but the stage object is created and includes an actual reference to a container element).

`stage.viewer.container` should be a plain div whose style can be changed by the user

> Additional question: what shall be done regarding tooltips? They are displayed on top of everything else and can overflow the viewer. I think this behaviour is nice as a cropped tooltip would not be informative, so I would favour keeping tooltips as they are.

totally agree, no cropped tooltip

**Comment by ppillot** [comment]
> `stage.viewer.container` should be a plain div whose style can be changed by the user
Meaning this div should be appended to the DOM at some stage? At present there is no code for handling that in viewer.ts (a div is created but not appended to the body of the page)

**Pull request merged**
