### PR TITLE
Av style surface

### PR DESCRIPTION
**Pull request by fredludlow**
Also see #205 

I've refactored this as one big closure now and it's much quicker!
Updated my version here:
http://fredludlow.com/ngldev/examples/webapp.html

On Chrome and IE11 on Windows this is comparable in speed to EDT at the same grid resolution. Firefox on Android gives similar speeds. For Chrome on Android it's still a factor of 2 or so slower... obviously...?! ;) 

This is probably a reasonable point to merge if you want to (and do please hammer the code into a better style if there's anything horrible looking in there* :)). There might be some performance gains to be had in projectTorus but it's no longer dominating the CPU profile.

*As an aside - what editor do you use? And can I copy your config file for it?

### CODE REVIEW

**Comment by arose** [comment]
Thanks, this is nice!

The scaling behavior seems to be worse than EDTsurf.
- 1AON: 23363.472ms (edt ms) vs 63317.274ms (av).
- 4V5A: 37093.969ms (edt ms) vs 75115.215ms (av).

The av surface for 4V5A also is incomplete, see below

screenshot 33

> *As an aside - what editor do you use? And can I copy your config file for it?

Just Sublime 3, with trailing spaces removal and spaces for indentation. I am thinking of using https://github.com/feross/standard to never think about code style again.

**Comment by fredludlow** [comment]
Hmm, will investigate...

**Comment by fredludlow** [comment]
I've not had a look at 4V58 yet, but for 1AON the profiler suggests SpatialHash.within is taking up most of the time - not sure why this would be...? It creates a new plain old JS array each time, maybe I can pass in a reusable array - I'll have a bit more of a hack (so far I've only managed to make it slower).

**Comment by arose** [comment]
Maybe a `eachWithin( callback )` method for spatial hash to avoid making temp arrays?

**Comment by fredludlow** [comment]
So I've improved the performance a bit, will tidy up and make another PR

I don't really understand why the "within" function dominates the profile for large systems - I suspect it's either something to do with pulling the bucket indices etc in and out of scope and cpu cache sizes and some other hand-waving explanations?? Or else allocating deallocating lots of small neighbour arrays (or some other form of handwaving..) :)

Anyway:  I made a version of SpatialHash that uses a grid size optimized for the problem (2.01 * maxRadius) - that means it has to use rounding rather than bitshifting but essentially the same code. 
I also added a withinRadii method which is aware of the atom radii and gives you a more precisely filtered list of neighbours - this saves a few million unnecessary checks later on. 

This is now faster than EDT ms on my box for 1aon and smaller examples (not quite as fast as EDT vws though).

On 4v5a I get out of memory errors with both methods unless I put the scaleFactor down to about 1.0.  EDT looks awful at that scaleFactor and also throws out-of-memory at higher scaleFactors... 

(The out of memory errors actually occur after building the surface - it's during allocation of the colour buffer for the surface triangles..)

I still haven't dug into why the surface colouring isn't working. 

Anyway - like I say, I'll make a PR and anxiously await a report of whether it's any better on your box :)

**Pull request merged**
