### PR TITLE
Fixes reference atom detection

### PR DESCRIPTION
**Pull request by fredludlow**
See #148

### CODE REVIEW

**Comment by arose** [comment]
Thank you!!

* for 4umt_47w I get - as expected - a "colinear reference atom" warning
* 1crn.mmtf and 2nc.sdf look good
* 4hhb.mmtf also, lots of rings
* added the basic colinearity handling you suggested
* added multipleBond support to line representation

I suggest to merge this now with master and make issues for anything we still want to do in future PRs.

Most of the code in `assignBondReferenceAtomIndices` and `propagateSearch` can probably live in a `BondGraph` class.

**Comment by arose** [comment]
> I suggest to merge this now with master and make issues for anything we still want to do in future PRs.

ping @fredludlow

**Comment by fredludlow** [comment]
Sounds good. Thanks again!

**Comment by arose** [comment]
all done, thanks

**Pull request merged**
