### PR TITLE
TS conversion effort for representations related modules

### PR DESCRIPTION
**Pull request by ppillot**
I open this PR to discuss and make suggestions about these conversions and how to best align them with NGL standards!
Comments welcome!

### CODE REVIEW

**Comment by ppillot** [comment]
Have found out where the error was. It's now functional!

**Comment by ppillot** [comment]
More conversions, related to surfaces

**Comment by arose** [comment]
Hi @ppillot is this ready to be merged?

**Comment by ppillot** [comment]
I think it was. My main concern was about the style and rigourness of the conversion.

**Comment by ppillot** [comment]
I've updated it with the latest changes from master and all checks have passed. I think it is ready for merging!

**Comment by ppillot** [comment]
This is the continuation of the TS conversion effort: this PR includes all the parsers.

**Comment by ppillot** [comment]
All the code has now been converted to TS (except for the polyfills)

**Comment by ppillot** [comment]
These last commits make NGL able to generate a d.ts file.
I have a concern with the code as I had to add imports in modules when a public function in it returns a member that is not defined in that module.
For example, a getAtom() returns an AtomProxy object, then TS needs to have it imported in the module even if it implicitly "knows" the type of the return. The side effect of this import is that it is then considered as an unused import! To prevent from writing the declaration for these functions output (which may be very complex and error prone), I've added dummy exports of types that include those imports. It won't affect the output of the JS code, but it's an ugly workaround...

**Comment by fredludlow** [comment]
Firstly, this is really great and much appreciated!

> For example, a getAtom() returns an AtomProxy object, then TS needs to have it imported in the module even if it implicitly "knows" the type of the return. The side effect of this import is that it is then considered as an unused import! To prevent from writing the declaration for these functions output (which may be very complex and error prone), I've added dummy exports of types that include those imports. It won't affect the output of the JS code, but it's an ugly workaround...

Do you get the unused import warning if you use AtomProxy as an explicit return type for the function that's returning the AtomProxy?

**Comment by ppillot** [comment]
> Do you get the unused import warning if you use AtomProxy as an explicit return type for the function that's returning the AtomProxy?
No, you're correct and as long as the function return type is as simple as that, this is the strategy I've used which is clean.

I've used it when the return type was complex. For example, in cylinder-buffer, one of the returned objects has the definition: 
```javascript
new CylinderGeometryBuffer(data: CylinderBufferData, params?: Partial<{
    radialSegments: number;
    openEnded: boolean;
} & {
    opaqueBack: boolean;
    side: BufferSide;
    opacity: number;
    depthWrite: boolean;
    clipNear: number;
    clipRadius: number;
    clipCenter: Vector3;      // <--- required import
    flatShaded: boolean;
    wireframe: boolean;
    roughness: number;
    metalness: number;
    diffuse: number;
    diffuseInterior: boolean;
    useInteriorColor: boolean;
    interiorColor: number;
    interiorDarkening: number;
    forceTransparent: boolean;
    matrix: Matrix4;             // <--- required import
    disablePicking: boolean;
    sortParticles: boolean;
    background: boolean;
}>): CylinderGeometryBuffer
```
It required me to import Vector3 and Matrix4 in the module and I did not want to replicate the whole structure as it is (tedious) error prone and not easily extendable if modifications are made to the code.
Maybe the best would be to add and interface in CylinderGeometryBuffer to name the type of this params object

**Comment by ppillot** [comment]
I've just tried it and got the following ts error: `error TS4023: Exported variable 'CylinderBufferDefaultParameters' has or is using name 'Vector3' from external module "/Users/... .../ngl/node_modules/@types/three/three-core" but cannot be named.`

**Comment by arose** [comment]
Hey, thank you so much, this is a great effort!

I merged it and made some changes to the build process to get a bundle. Also, I removed to dummy variables as I did not quite got why the where there (but that might be my ignorance, its in an easily reversible commit), at least I did not get any unused import errors (but I also updated to ts 3.0.1).

**Comment by ppillot** [comment]
You're most welcome! 
Have you been able to get a (or a list of) proper declaration file? The dummy imports were there for this reason.

I've tried several options for the declaration(s) file(s) and could not find something entirely satisfactory.
Here is what I've tried

1. in tsconfig, adding a `declaration: true` and a `declarationDir: "types"`
This outputs a declaration file for each module in NGL. I added a `types` property to package.json. When I consume these declarations file in my own projects, I can import the regular modules from NGL (e.g. Selection, ColorMaker,...) and I can import declarations for other modules returned by these modules such as BitArray or AtomProxy with a syntax such as `import BitArray from "../../npm_modules/ngl/utils/bitarray`
2. in a specific ts config file, adding a `declaration: true`, `emitDeclarationOnly: true`, `outFile: "ngl.d.ts"`, `module: AMD`
This outputs a single declaration file containing all the modules from NGL. When I consume this d.ts in my own projects, I can import the regular modules from NGL (e.g. Selection, ColorMaker,...) and I can import declarations for other modules with a syntax such as `import BitArray from "utils/bitarray"` which seems like a nonsense to me as this doesn't exist. I'd prefer have a reference to this module under ngl namespace.
3. I've tried the library dts-bundle which should concat the declarations, with no success
4. I've tried the library dts-generator which under the hood uses the output from the TS compiler. It generates a single file with declarations under a prefix. The problem is that I have to change my import declarations in my project to `import {Selection} from "ngl/src/ngl"` (I thing I could get rid of the src part, but not of the double ngl...) which means breaking with every existing code relying on this kind of import.

So, it seems to me that option 1 is the best of these, even if it's still not perfect (it means shipping hundreds of declaration file with the npm package) as the imports would have a correct syntax.
What is your opinion?

**Comment by ppillot** [comment]
I've tried to output a d.ts file from the latest code on github (`tsc -d --outFile "build/types/ngl.js" --module "system" --emitDeclarationOnly`) and I get the same errors as before the dummy imports trick, plus a couple due to webvr (easily fixable):
```terminal
$ tsc -d --outFile "build/types/ngl.js" --module "system" --emitDeclarationOnly
src/buffer/cylinder-buffer.ts(19,14): error TS4023: Exported variable 'CylinderBufferDefaultParameters' has or is using name 'Matrix4' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/cylinder-buffer.ts(19,14): error TS4023: Exported variable 'CylinderBufferDefaultParameters' has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/cylinderimpostor-buffer.ts(16,14): error TS4023: Exported variable 'CylinderImpostorBufferDefaultParameters' has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/cylinderimpostor-buffer.ts(39,7): error TS4041: Return type of public getter 'defaultParameters' from exported class has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/doublesided-buffer.ts(95,7): error TS4036: Parameter type of public setter 'matrix' from exported class has or is using name 'Matrix4' from private module '"/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core"'.
src/buffer/doublesided-buffer.ts(106,7): error TS4041: Return type of public getter 'parameters' from exported class has or is using name 'Matrix4' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/doublesided-buffer.ts(106,7): error TS4041: Return type of public getter 'parameters' from exported class has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/doublesided-buffer.ts(110,3): error TS4053: Return type of public method from exported class has or is using name 'Matrix4' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/doublesided-buffer.ts(110,3): error TS4053: Return type of public method from exported class has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/geometry-buffer.ts(78,34): error TS4061: Parameter 'params' of constructor from exported class has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/hyperballstick-buffer.ts(21,14): error TS4023: Exported variable 'HyperballStickBufferDefaultParameters' has or isusing name 'Matrix4' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot benamed.
src/buffer/hyperballstick-buffer.ts(21,14): error TS4023: Exported variable 'HyperballStickBufferDefaultParameters' has or isusing name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot benamed.
src/buffer/hyperballstickimpostor-buffer.ts(23,14): error TS4023: Exported variable 'HyperballStickImpostorBufferDefaultParameters' has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/hyperballstickimpostor-buffer.ts(47,7): error TS4041: Return type of public getter 'defaultParameters' from exported class has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/image-buffer.ts(41,14): error TS4023: Exported variable 'ImageBufferDefaultParameters' has or is using name 'Matrix4' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/image-buffer.ts(41,14): error TS4023: Exported variable 'ImageBufferDefaultParameters' has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/image-buffer.ts(56,7): error TS4041: Return type of public getter 'defaultParameters' from exported class has or is using name 'Matrix4' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/image-buffer.ts(56,7): error TS4041: Return type of public getter 'defaultParameters' from exported class has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/point-buffer.ts(63,14): error TS4023: Exported variable 'PointBufferDefaultParameters' has or is using name 'Matrix4' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/point-buffer.ts(63,14): error TS4023: Exported variable 'PointBufferDefaultParameters' has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/point-buffer.ts(95,7): error TS4041: Return type of public getter 'defaultParameters' from exported class has or is using name 'Matrix4' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/point-buffer.ts(95,7): error TS4041: Return type of public getter 'defaultParameters' from exported class has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/sphere-buffer.ts(16,14): error TS4023: Exported variable 'SphereBufferDefaultParameters' has or is using name 'Matrix4' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/sphere-buffer.ts(16,14): error TS4023: Exported variable 'SphereBufferDefaultParameters' has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/text-buffer.ts(288,14): error TS4023: Exported variable 'TextBufferDefaultParameters' has or is using name 'Matrix4' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/text-buffer.ts(288,14): error TS4023: Exported variable 'TextBufferDefaultParameters' has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/text-buffer.ts(349,7): error TS4041: Return type of public getter 'defaultParameters' from exported class has or is using name 'Matrix4' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/text-buffer.ts(349,7): error TS4041: Return type of public getter 'defaultParameters' from exported class has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/tubemesh-buffer.ts(23,14): error TS4023: Exported variable 'TubeMeshBufferDefaultParameters' has or is using name 'Matrix4' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/tubemesh-buffer.ts(55,7): error TS4041: Return type of public getter 'defaultParameters' from exported class has or is using name 'Matrix4' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/vector-buffer.ts(24,14): error TS4023: Exported variable 'VectorBufferDefaultParameters' has or is using name 'Matrix4' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/vector-buffer.ts(24,14): error TS4023: Exported variable 'VectorBufferDefaultParameters' has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/vector-buffer.ts(34,7): error TS4041: Return type of public getter 'defaultParameters' from exported class has or is using name 'Matrix4' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/vector-buffer.ts(34,7): error TS4041: Return type of public getter 'defaultParameters' from exported class has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/wideline-buffer.ts(22,14): error TS4023: Exported variable 'WideLineBufferDefaultParameters' has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/buffer/wideline-buffer.ts(44,7): error TS4041: Return type of public getter 'defaultParameters' from exported class has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/geometry/shape.ts(28,14): error TS4023: Exported variable 'ShapeDefaultParameters' has or is using name 'Matrix4' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/parser/xml-parser.ts(41,3): error TS4053: Return type of public method from exported class has or is using name 'XMLNode'from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/utils/parse-xml" but cannot be named.
src/representation/ballandstick-representation.ts(152,3): error TS4053: Return type of public method from exported class has or is using name 'Surface' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/surface/surface" but cannot be named.
src/representation/ballandstick-representation.ts(152,3): error TS4053: Return type of public method from exported class has or is using name 'Volume' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/surface/volume" but cannot be named.
src/representation/ballandstick-representation.ts(163,3): error TS4053: Return type of public method from exported class has or is using name 'Surface' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/surface/surface" but cannot be named.
src/representation/ballandstick-representation.ts(163,3): error TS4053: Return type of public method from exported class has or is using name 'Volume' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/surface/volume" but cannot be named.
src/representation/contact-representation.ts(238,3): error TS4053: Return type of public method from exported class has or isusing name 'ContactPicker' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/utils/picker" but cannot be named.
src/representation/hyperball-representation.ts(62,3): error TS4053: Return type of public method from exported class has or is using name 'Surface' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/surface/surface" but cannot be named.
src/representation/hyperball-representation.ts(62,3): error TS4053: Return type of public method from exported class has or is using name 'Volume' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/surface/volume" but cannot be named.
src/representation/line-representation.ts(152,3): error TS4053: Return type of public method from exported class has or is using name 'BondDataFields' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/structure/structure-data" but cannot be named.
src/representation/line-representation.ts(152,3): error TS4053: Return type of public method from exported class has or is using name 'BondDataParams' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/structure/structure-data" but cannot be named.
src/representation/line-representation.ts(152,3): error TS4053: Return type of public method from exported class has or is using name 'Surface' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/surface/surface" but cannot be named.
src/representation/line-representation.ts(152,3): error TS4053: Return type of public method from exported class has or is using name 'Volume' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/surface/volume" but cannot be named.
src/representation/measurement-representation.ts(290,3): error TS4053: Return type of public method from exported class has or is using name 'Matrix4' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/representation/measurement-representation.ts(290,3): error TS4053: Return type of public method from exported class has or is using name 'Vector3' from external module "/Users/paul0/Sites/ngl-ts2/ngl/node_modules/@types/three/three-core" but cannot be named.
src/representation/molecularsurface-representation.ts(341,3): error TS4053: Return type of public method from exported class has or is using name 'Volume' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/surface/volume" but cannot be named.
src/representation/structure-representation.ts(269,3): error TS4053: Return type of public method from exported class has or is using name 'Surface' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/surface/surface" but cannot be named.
src/representation/structure-representation.ts(269,3): error TS4053: Return type of public method from exported class has or is using name 'Volume' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/surface/volume" but cannot be named.
src/representation/structure-representation.ts(285,3): error TS4053: Return type of public method from exported class has or is using name 'Surface' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/surface/surface" but cannot be named.
src/representation/structure-representation.ts(285,3): error TS4053: Return type of public method from exported class has or is using name 'Volume' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/surface/volume" but cannot be named.
src/representation/structure-representation.ts(293,3): error TS4053: Return type of public method from exported class has or is using name 'Surface' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/surface/surface" but cannot be named.
src/representation/structure-representation.ts(293,3): error TS4053: Return type of public method from exported class has or is using name 'Volume' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/surface/volume" but cannot be named.
src/representation/surface-representation.ts(387,3): error TS4053: Return type of public method from exported class has or isusing name 'ColormakerParameters' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/color/colormaker" but cannot be named.
src/representation/unitcell-representation.ts(69,3): error TS4053: Return type of public method from exported class has or isusing name 'UnitcellPicker' from external module "/Users/paul0/Sites/ngl-ts2/ngl/src/utils/picker" but cannot be named.
types/webvr-api/index.d.ts(136,5): error TS2717: Subsequent property declarations must have the same type.  Property 'leftBounds' must be of type 'number[] | null | undefined', but here has type 'Float32Array | number[] | null | undefined'.
types/webvr-api/index.d.ts(137,5): error TS2717: Subsequent property declarations must have the same type.  Property 'rightBounds' must be of type 'number[] | null | undefined', but here has type 'Float32Array | number[] | null | undefined'.
```

**Comment by garyo** [comment]
I'm interested in this as well. I tried `tsc -d --outfile ngl.esm.js --module system -emitDeclarationOnly` and it does generate a .d.ts (with some errors), but it has some problems when used, such as relative import names which are not allowed in an ambient module declaration. I then tried @ppillot 's option 1 (as best I could) and got something that looks OK (I copied the generated `types` folder into dist), but it does have many errors. @ppillot do you have a PR or a patch with where you've gotten to with your option 1? That seems like the best way to go. I'd be happy to collaborate on this.

Also I'm integrating with Three.js, so I will probably need to build my own NGL with the same version of Three I'm using anyway (it's under active development and I can already see some errors due to recent changes).

**Comment by ppillot** [comment]
Hi @garyo , I have not touched this for a few months now... I think the further I got was with my branch dts3 back in September https://github.com/ppillot/ngl/tree/dts3

I now think there is a concern with the way the module is compiled: the `system` parameter used in the command line does not produce a regular ES6 module (but a SystemJS compliant one instead), but it was the only way I had found to produce a single file module. Declarations files instead are output in separate files on a per module basis as you had noticed.
I think that ultimately the goal would be to output proper ES6 modules so that they can be loaded directly in compliant browsers and also so that one can do some tree shaking when using a bundler such as WebPack. I am not sure about how that would go with your objective of perusing a specific three.js version....

**Comment by garyo** [comment]
OK, thanks -- I'm trying your dts3 branch now. 
One small weirdness: when running a regular build on your branch, I had to hand-modify `node_modules/@types/webvr-api/index.d.ts` (I know, not even part of this package) to fix typescript errors. Not sure what's up with that. Although when I installed the latest three 0.103.0 (which has full type decls) I could uninstall `@types/three`, so we don't need `@types/webvr-api` anymore -- so that's good. But that introduces some incompatibilities I'll look into fixing. Nothing too serious...

**Comment by garyo** [comment]
I have a version that works for me now, based on three 0.103.0, with complete types and no errors in my app! You can browse it at https://github.com/garyo/ngl/commit/a462b2e -- I'd appreciate any feedback.

Also I agree with you about creating ES6 modules -- right now built ngl includes a whole copy of three.js for instance. I'm using webpack so modules would be way better for me.

**Comment by garyo** [comment]
@ppillot, have you submitted a PR for your https://github.com/ppillot/ngl/tree/dts3 branch? I need it (since I'm using typescript) and as noted above, it is working fine for me, generating full type decls.

I have a PR pending to update NGL to three.js r103 (which I need for other reasons, but NGL and my code have to agree on the three.js version -- I'll probably update it to support the most recent r106 before submitting it here), but it depends on that dts3 branch.

**Pull request merged**
