### PR TITLE
Build ES module file

### PR DESCRIPTION
**Pull request by ppillot**
Changes to the build process to produce an ES module that can be consumed by bundlers (such as rollup and webpack).

### CODE REVIEW

**Comment by arose** [comment]
see also https://github.com/rollup/rollup/wiki/pkg.module

**Comment by arose** [comment]
@ppillot just to make sure. Is this ready to go?

**Comment by ppillot** [comment]
I think it is. I've tried it on my web application, using webpack and it works (no error).
I haven't noticed any tree shaking effect. I suppose it works fine, at least it works as the other es modules I use.

**Comment by arose** [comment]
> I haven't noticed any tree shaking effect.

I would expect the treeshaking when creating the bundle of the application that consumes NGL.

> I suppose it works fine, at least it works as the other es modules I use.

That is good enough for me :)

**Comment by ppillot** [comment]
Tree shaking is indeed sort of working: when importing only the used objects in NGL, the module's size is decreased... by 10kB (that's 2kB less gzipped)

**Comment by arose** [comment]
I think the way I import and register parsers, representations and colormakers prevents treeshaking for them. Unless you edit the ngl.js entry point you always get almost everything of the library.

**Pull request merged**
